/*
 * File: app/view/AgentGridPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AgentGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.agentgridpanel',

    requires: [
        'MyApp.view.AgentGridPanelViewModel',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'agentgridpanel'
    },
    id: 'agentGridPanel',
    padding: '0 10',

    bind: {
        store: '{agentStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'userAgent',
            text: 'User Agent',
            flex: 3
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'agentName',
            text: 'Agent Name',
            flex: 1
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'osName',
            text: 'OS Name',
            flex: 1
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            bind: {
                store: '{agentStore}'
            }
        }
    ]

});