/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'MyApp.view.MainViewViewModel',
        'MyApp.view.MainViewViewController',
        'Ext.form.Label',
        'Ext.menu.Menu',
        'Ext.menu.Separator'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'container',
            region: 'north',
            height: 50,
            itemId: 'headerContainer',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'headerTitle',
                    style: {
                        padding: '15px 0 10px 10px',
                        'font-size': '18px',
                        'font-weight': 'bold',
                        color: 'white'
                    },
                    items: [
                        {
                            xtype: 'label',
                            text: 'Log Visualization'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            itemId: 'menuPanel',
            width: 150,
            bodyBorder: false,
            collapseDirection: 'left',
            collapsible: true,
            title: 'Menu',
            items: [
                {
                    xtype: 'menu',
                    floating: false,
                    itemId: 'sideMenu',
                    listeners: {
                        beforehide: 'onSideMenuBeforeHide'
                    },
                    items: [
                        {
                            xtype: 'menuitem',
                            text: 'Log List',
                            focusable: true,
                            listeners: {
                                click: 'onLogListClick'
                            }
                        },
                        {
                            xtype: 'menuseparator'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Agent List',
                            focusable: true,
                            listeners: {
                                click: 'onAgentListClick'
                            }
                        },
                        {
                            xtype: 'menuseparator'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Top 10 Domains',
                            listeners: {
                                click: 'onMenuitemClick'
                            }
                        },
                        {
                            xtype: 'menuseparator'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Top 10 Referer Domains',
                            listeners: {
                                click: 'onMenuitemClick2'
                            }
                        },
                        {
                            xtype: 'menuseparator'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Access by Hour',
                            listeners: {
                                click: 'onMenuitemClick1'
                            }
                        },
                        {
                            xtype: 'menuseparator'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Access by Date',
                            listeners: {
                                click: 'onMenuitemClick11'
                            }
                        },
                        {
                            xtype: 'menuseparator'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Access by Day',
                            listeners: {
                                click: 'onMenuitemClick111'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            split: true,
            itemId: 'contentPanel',
            layout: 'fit',
            title: 'Content'
        }
    ]

});