/*
 * File: app/view/AgentGridPanelViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AgentGridPanelViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.agentgridpanel',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    stores: {
        agentStore: {
            autoLoad: true,
            proxy: {
                type: 'ajax',
                url: '/agentController/getAgents',
                reader: {
                    type: 'json',
                    rootProperty: 'records'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'agentName'
                },
                {
                    name: 'osName'
                },
                {
                    name: 'userAgent'
                }
            ]
        }
    }

});