/*
 * File: app/view/DateAreaChart.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DateAreaChart', {
    extend: 'Ext.chart.CartesianChart',
    alias: 'widget.dateareachart',

    requires: [
        'MyApp.view.HourAreaChartViewModel1',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Area',
        'Ext.chart.interactions.PanZoom'
    ],

    viewModel: {
        type: 'dateareachart'
    },
    padding: '10 0 0 0',
    insetPadding: 40,

    bind: {
        store: '{dateStore}'
    },
    axes: [
        {
            type: 'category',
            fields: [
                'date'
            ],
            grid: true,
            label: {
                rotate: {
                    degrees: -45
                }
            },
            title: 'Date',
            position: 'bottom'
        },
        {
            type: 'numeric',
            fields: [
                'numOfRequest'
            ],
            grid: true,
            position: 'left',
            title: 'Number of Requests'
        }
    ],
    series: [
        {
            type: 'area',
            tooltip: {
                trackMouse: true,
                style: 'background: #FFF',
                height: 20,
                renderer: function(storeItem, item) {
                    this.setTitle(storeItem.get('date') + ': ' + storeItem.get('numOfRequest'));
                }
            },
            xField: 'date',
            yField: [
                'numOfRequest'
            ]
        }
    ],
    interactions: [
        {
            type: 'panzoom'
        }
    ]

});