/*
 * File: app/view/LogGridPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LogGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.loggridpanel',

    requires: [
        'MyApp.view.LogGridPanelViewModel',
        'Ext.grid.column.Date',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'loggridpanel'
    },
    id: 'logGridPanel',
    padding: '0 10',

    bind: {
        store: '{logStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'clientIP',
            text: 'IP'
        },
        {
            xtype: 'datecolumn',
            dataIndex: 'date',
            text: 'Date'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'time',
            text: 'Time'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'accessURL',
            text: 'Access URL',
            flex: 1
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'referer',
            text: 'Referer'
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            bind: {
                store: '{logStore}'
            }
        }
    ]

});