/*
 * File: app/view/MainViewViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainview',

    onSideMenuBeforeHide: function(component, eOpts) {
        return false;
    },

    onLogListClick: function(item, e, eOpts) {
        var contentPanel = this.getView().getComponent("contentPanel");
        contentPanel.setTitle("List of Logs");

        var logGridPanel = Ext.create("MyApp.view.LogGridPanel");

        contentPanel.removeAll();
        contentPanel.add(logGridPanel);
        contentPanel.doLayout();
    },

    onAgentListClick: function(item, e, eOpts) {

        var contentPanel = this.getView().getComponent("contentPanel");
        contentPanel.setTitle("List of Agents");

        var agentGridPanel = Ext.create("MyApp.view.AgentGridPanel");

        contentPanel.removeAll();
        contentPanel.add(agentGridPanel);
        contentPanel.doLayout();
    },

    onMenuitemClick: function(item, e, eOpts) {
        // debugger;
        var contentPanel = this.getView().getComponent("contentPanel");
        contentPanel.setLoading(true);

        contentPanel.setTitle("Top 10 Domains");

        var domainChart = Ext.create("MyApp.view.DomainChart");

        contentPanel.removeAll();
        contentPanel.add(domainChart);
        contentPanel.doLayout();

        setTimeout(function(){

            var domainStore = domainChart.getStore();
            //     debugger;
            domainStore.load({
                callback: function(records, operation, success) {
                    console.log(success);
                    console.log(records.length);
                    if (success == true) {

                        domainChart.redraw();
                        domainChart.doLayout();


                        contentPanel.setLoading(false);
                        //                 debugger;
                    } else {
                        // the store didn't load, deal with it
                        alert('Error!');
                    }

                },
                scope: this
            });
        }, 500);


    },

    onMenuitemClick2: function(item, e, eOpts) {
        var contentPanel = this.getView().getComponent("contentPanel");
        contentPanel.setLoading(true);

        contentPanel.setTitle("Top 10 Referer Domains");

        var refererDomainChart = Ext.create("MyApp.view.RefererDomainChart");

        contentPanel.removeAll();
        contentPanel.add(refererDomainChart);
        contentPanel.doLayout();

        setTimeout(function(){

            var refererDomainStore = refererDomainChart.getStore();

            refererDomainStore.load({
                callback: function(records, operation, success) {

                    if (success == true) {

                        refererDomainChart.redraw();
                        refererDomainChart.doLayout();

                        contentPanel.setLoading(false);

                    } else {
                        // the store didn't load, deal with it
                        alert('Error!');
                    }

                },
                scope: this
            });
        }, 500);


    },

    onMenuitemClick1: function(item, e, eOpts) {
        var contentPanel = this.getView().getComponent("contentPanel");
        contentPanel.setLoading(true);

        contentPanel.setTitle("Access by Hour");

        var hourAreaChart = Ext.create("MyApp.view.HourAreaChart");

        contentPanel.removeAll();
        contentPanel.add(hourAreaChart);
        contentPanel.doLayout();

        setTimeout(function(){

            var hourStore = hourAreaChart.getStore();

            hourStore.load({
                callback: function(records, operation, success) {
                    console.log(success);
                    console.log(records.length);
                    if (success == true) {

                        hourAreaChart.redraw();
                        hourAreaChart.doLayout();

                        contentPanel.setLoading(false);
                    } else {
                        // the store didn't load, deal with it
                        alert('Error!');
                    }

                },
                scope: this
            });
        }, 500);


    },

    onMenuitemClick11: function(item, e, eOpts) {
        var contentPanel = this.getView().getComponent("contentPanel");
        contentPanel.setLoading(true);

        contentPanel.setTitle("Access by Date");

        var dateAreaChart = Ext.create("MyApp.view.DateAreaChart");

        contentPanel.removeAll();
        contentPanel.add(dateAreaChart);
        contentPanel.doLayout();

        setTimeout(function(){

            var dateStore = dateAreaChart.getStore();

            dateStore.load({
                callback: function(records, operation, success) {
                    console.log(success);
                    console.log(records.length);
                    if (success == true) {

                        dateAreaChart.redraw();
                        dateAreaChart.doLayout();

                        contentPanel.setLoading(false);
                    } else {
                        // the store didn't load, deal with it
                        alert('Error!');
                    }

                },
                scope: this
            });
        }, 500);


    },

    onMenuitemClick111: function(item, e, eOpts) {
        var contentPanel = this.getView().getComponent("contentPanel");
        contentPanel.setLoading(true);

        contentPanel.setTitle("Access by Day");

        var dayNameAreaChart = Ext.create("MyApp.view.DayNameAreaChart");

        contentPanel.removeAll();
        contentPanel.add(dayNameAreaChart);
        contentPanel.doLayout();

        setTimeout(function(){

            var dayNameStore = dayNameAreaChart.getStore();

            dayNameStore.load({
                callback: function(records, operation, success) {

                    if (success == true) {

                        dayNameAreaChart.redraw();
                        dayNameAreaChart.doLayout();

                        contentPanel.setLoading(false);
                    } else {
                        // the store didn't load, deal with it
                        alert('Error!');
                    }

                },
                scope: this
            });
        }, 500);


    }

});
